### ISSUE TITLE
Bug: A DSN is leaked in main.py

### ISSUE THREAD

**Issue by markovejnovic** [gitautoai/gitauto#299]
### Bug Behavior

It appears that `gitauto` holds a reference to your Sentry DSN. This can potentially cost non-insignificant amounts of money as someone can submit events to your DSN, to my understanding. If you are hosting data on the sentry cloud, I could be wrong, but I assume this will cost real money.

I tried `POST`ing but that failed so maybe this is not a present concern.

### Logs

N/A

### When It Occurred

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Device

N/A

### OS

Linux

### Browser

N/A

**Comment by hiroshinishio** [comment]
@markovejnovic Oh my god, thank you Marko, and thank you for creating a PR!
